# Generated by Django 5.0.1 on 2024-01-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="full_name",
            field=models.CharField(max_length=1000),
        ),
    ]
