# Generated by Django 4.2.6 on 2023-12-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="updated_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="cartitems",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="cartitems",
            name="updated_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="updated_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="pizzacategory",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="pizzacategory",
            name="updated_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
