# Generated by Django 4.2.6 on 2023-12-16 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0002_alter_recipe_recipe_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="recipe_description",
            new_name="recipe_desc",
        ),
    ]
