# Generated by Django 4.2.6 on 2023-12-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0004_recipe_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="recipe_view_count",
            field=models.IntegerField(default=1),
        ),
    ]
