# Generated by Django 4.2.6 on 2023-12-21 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0005_recipe_recipe_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(
                default=datetime.datetime(
                    2023, 12, 21, 17, 32, 57, 879560, tzinfo=datetime.timezone.utc
                ),
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
