# Generated by Django 5.0 on 2023-12-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0006_recipe_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
