# Generated by Django 5.0 on 2024-01-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netflixapp", "0002_alter_movie_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="video",
            field=models.ManyToManyField(to="netflixapp.video"),
        ),
    ]
