# Generated by Django 4.2.6 on 2023-12-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campusHub", "0004_alter_reportcard_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportcard",
            name="date_of_report_card_generation",
            field=models.DateField(auto_now_add=True),
        ),
    ]
