# Generated by Django 5.0 on 2023-12-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campusHub", "0005_alter_reportcard_date_of_report_card_generation"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
